"""Initial schema

Revision ID: 14dbcf303b03
Revises: 
Create Date: 2026-06-27 18:10:16.049716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14dbcf303b03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_name'), ['name'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('EXCEL', 'PDF', 'IMAGE', 'EMAIL', 'PORTAL', 'HANDWRITTEN', name='documentsource', native_enum=False), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PARSED', 'FAILED', name='documentstatus', native_enum=False), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_employee_code'), ['employee_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_id'), ['id'], unique=False)

    op.create_table('document_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_extractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_extractions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extractions_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extractions_id'), ['id'], unique=False)

    op.create_table('payroll_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ot_rate_per_hour', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payroll_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_master_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_master_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_master_id'), ['id'], unique=False)

    op.create_table('timesheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'VALIDATION_PENDING', 'VALIDATED', 'APPROVED', 'INVOICED', name='timesheetstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timesheets_billing_month'), ['billing_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_timesheets_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timesheets_id'), ['id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('timesheet_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('service_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PAID', 'OVERDUE', 'VOID', name='invoicestatus', native_enum=False), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_timesheet_id'), ['timesheet_id'], unique=True)

    op.create_table('timesheet_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timesheet_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('raw_employee_code', sa.String(length=50), nullable=True),
    sa.Column('raw_employee_name', sa.String(length=200), nullable=True),
    sa.Column('working_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ot_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('leave_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timesheet_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timesheet_entries_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timesheet_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timesheet_entries_timesheet_id'), ['timesheet_id'], unique=False)

    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ot_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bill_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_items_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_items_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timesheet_entry_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('FAILED', 'PASSED', name='validationstatus', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('ERROR', 'WARNING', 'INFO', name='validationseverity', native_enum=False), nullable=False),
    sa.Column('expected', sa.Text(), nullable=True),
    sa.Column('actual', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['timesheet_entry_id'], ['timesheet_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_results_rule_name'), ['rule_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_results_timesheet_entry_id'), ['timesheet_entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_results_timesheet_entry_id'))
        batch_op.drop_index(batch_op.f('ix_validation_results_rule_name'))
        batch_op.drop_index(batch_op.f('ix_validation_results_id'))

    op.drop_table('validation_results')
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_items_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_items_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_items_employee_id'))

    op.drop_table('invoice_items')
    with op.batch_alter_table('timesheet_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timesheet_entries_timesheet_id'))
        batch_op.drop_index(batch_op.f('ix_timesheet_entries_id'))
        batch_op.drop_index(batch_op.f('ix_timesheet_entries_employee_id'))

    op.drop_table('timesheet_entries')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_timesheet_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_client_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timesheets_id'))
        batch_op.drop_index(batch_op.f('ix_timesheets_client_id'))
        batch_op.drop_index(batch_op.f('ix_timesheets_billing_month'))

    op.drop_table('timesheets')
    with op.batch_alter_table('payroll_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_master_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_master_employee_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_master_client_id'))

    op.drop_table('payroll_master')
    with op.batch_alter_table('document_extractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_extractions_id'))
        batch_op.drop_index(batch_op.f('ix_document_extractions_field_name'))
        batch_op.drop_index(batch_op.f('ix_document_extractions_document_id'))

    op.drop_table('document_extractions')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_id'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_code'))
        batch_op.drop_index(batch_op.f('ix_employees_client_id'))

    op.drop_table('employees')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_client_id'))

    op.drop_table('documents')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_name'))
        batch_op.drop_index(batch_op.f('ix_clients_id'))

    op.drop_table('clients')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
