"""Add configs jobs and layout columns

Revision ID: 7b428e462712
Revises: 14dbcf303b03
Create Date: 2026-06-27 19:43:01.273884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b428e462712'
down_revision: Union[str, Sequence[str], None] = '14dbcf303b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('service_charge_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_working_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_ot_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('invoice_prefix', sa.String(length=10), nullable=False),
    sa.Column('dispatch_method', sa.String(length=50), nullable=False),
    sa.Column('validation_profile', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    with op.batch_alter_table('client_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_configs_id'), ['id'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('UPLOAD', 'OCR', 'PARSER', 'NORMALIZER', 'VALIDATION', 'INVOICE', 'DISPATCH', name='jobstage', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('worker_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_id'), ['id'], unique=False)

    with op.batch_alter_table('document_extractions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('column_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('entity_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('invoice_pdf_path', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='invoiceapprovalstatus', native_enum=False), nullable=False))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_year', sa.Integer(), nullable=False))
        batch_op.alter_column('billing_month',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_timesheets_billing_year'), ['billing_year'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timesheets_billing_year'))
        batch_op.alter_column('billing_month',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('billing_year')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approval_status')
        batch_op.drop_column('invoice_pdf_path')
        batch_op.drop_column('currency')
        batch_op.drop_column('due_date')
        batch_op.drop_column('invoice_date')

    with op.batch_alter_table('document_extractions', schema=None) as batch_op:
        batch_op.drop_column('entity_type')
        batch_op.drop_column('column_name')
        batch_op.drop_column('row_number')

    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_document_id'))

    op.drop_table('processing_jobs')
    with op.batch_alter_table('client_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_configs_id'))

    op.drop_table('client_configs')
    # ### end Alembic commands ###
