"""add_salary_overrides_to_timesheet_entry

Revision ID: d9eb43bc0a80
Revises: 7b428e462712
Create Date: 2026-06-28 04:08:16.788133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9eb43bc0a80'
down_revision: Union[str, Sequence[str], None] = '7b428e462712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_basic', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('salary_allowance', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('salary_deduction', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('salary_ot_amount', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet_entries', schema=None) as batch_op:
        batch_op.drop_column('salary_ot_amount')
        batch_op.drop_column('salary_deduction')
        batch_op.drop_column('salary_allowance')
        batch_op.drop_column('salary_basic')

    # ### end Alembic commands ###
