/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientUploadPayrollRouteImport } from './routes/client.upload-payroll'
import { Route as ClientUploadHistoryRouteImport } from './routes/client.upload-history'
import { Route as ClientQueriesRouteImport } from './routes/client.queries'
import { Route as ClientInvoicesRouteImport } from './routes/client.invoices'
import { Route as ClientDashboardRouteImport } from './routes/client.dashboard'
import { Route as AdminQueriesRouteImport } from './routes/admin.queries'
import { Route as AdminPayrollQueueRouteImport } from './routes/admin.payroll-queue'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminHumanReviewRouteImport } from './routes/admin.human-review'
import { Route as AdminDispatchRouteImport } from './routes/admin.dispatch'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAgentRouteImport } from './routes/admin.agent'
import { Route as AdminPayrollQueueIdRouteImport } from './routes/admin.payroll-queue.$id'
import { Route as AdminClientsIdRouteImport } from './routes/admin.clients.$id'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientUploadPayrollRoute = ClientUploadPayrollRouteImport.update({
  id: '/upload-payroll',
  path: '/upload-payroll',
  getParentRoute: () => ClientRoute,
} as any)
const ClientUploadHistoryRoute = ClientUploadHistoryRouteImport.update({
  id: '/upload-history',
  path: '/upload-history',
  getParentRoute: () => ClientRoute,
} as any)
const ClientQueriesRoute = ClientQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => ClientRoute,
} as any)
const ClientInvoicesRoute = ClientInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const AdminQueriesRoute = AdminQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollQueueRoute = AdminPayrollQueueRouteImport.update({
  id: '/payroll-queue',
  path: '/payroll-queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHumanReviewRoute = AdminHumanReviewRouteImport.update({
  id: '/human-review',
  path: '/human-review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDispatchRoute = AdminDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentRoute = AdminAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollQueueIdRoute = AdminPayrollQueueIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPayrollQueueRoute,
} as any)
const AdminClientsIdRoute = AdminClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/admin/agent': typeof AdminAgentRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/human-review': typeof AdminHumanReviewRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/payroll-queue': typeof AdminPayrollQueueRouteWithChildren
  '/admin/queries': typeof AdminQueriesRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/invoices': typeof ClientInvoicesRoute
  '/client/queries': typeof ClientQueriesRoute
  '/client/upload-history': typeof ClientUploadHistoryRoute
  '/client/upload-payroll': typeof ClientUploadPayrollRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/payroll-queue/$id': typeof AdminPayrollQueueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/admin/agent': typeof AdminAgentRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/human-review': typeof AdminHumanReviewRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/payroll-queue': typeof AdminPayrollQueueRouteWithChildren
  '/admin/queries': typeof AdminQueriesRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/invoices': typeof ClientInvoicesRoute
  '/client/queries': typeof ClientQueriesRoute
  '/client/upload-history': typeof ClientUploadHistoryRoute
  '/client/upload-payroll': typeof ClientUploadPayrollRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/payroll-queue/$id': typeof AdminPayrollQueueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/admin/agent': typeof AdminAgentRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/human-review': typeof AdminHumanReviewRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/payroll-queue': typeof AdminPayrollQueueRouteWithChildren
  '/admin/queries': typeof AdminQueriesRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/invoices': typeof ClientInvoicesRoute
  '/client/queries': typeof ClientQueriesRoute
  '/client/upload-history': typeof ClientUploadHistoryRoute
  '/client/upload-payroll': typeof ClientUploadPayrollRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/payroll-queue/$id': typeof AdminPayrollQueueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/client'
    | '/contact'
    | '/features'
    | '/login'
    | '/pricing'
    | '/admin/agent'
    | '/admin/analytics'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/dispatch'
    | '/admin/human-review'
    | '/admin/invoices'
    | '/admin/payroll-queue'
    | '/admin/queries'
    | '/client/dashboard'
    | '/client/invoices'
    | '/client/queries'
    | '/client/upload-history'
    | '/client/upload-payroll'
    | '/admin/clients/$id'
    | '/admin/payroll-queue/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/client'
    | '/contact'
    | '/features'
    | '/login'
    | '/pricing'
    | '/admin/agent'
    | '/admin/analytics'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/dispatch'
    | '/admin/human-review'
    | '/admin/invoices'
    | '/admin/payroll-queue'
    | '/admin/queries'
    | '/client/dashboard'
    | '/client/invoices'
    | '/client/queries'
    | '/client/upload-history'
    | '/client/upload-payroll'
    | '/admin/clients/$id'
    | '/admin/payroll-queue/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/client'
    | '/contact'
    | '/features'
    | '/login'
    | '/pricing'
    | '/admin/agent'
    | '/admin/analytics'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/dispatch'
    | '/admin/human-review'
    | '/admin/invoices'
    | '/admin/payroll-queue'
    | '/admin/queries'
    | '/client/dashboard'
    | '/client/invoices'
    | '/client/queries'
    | '/client/upload-history'
    | '/client/upload-payroll'
    | '/admin/clients/$id'
    | '/admin/payroll-queue/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRoute
  ClientRoute: typeof ClientRouteWithChildren
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/upload-payroll': {
      id: '/client/upload-payroll'
      path: '/upload-payroll'
      fullPath: '/client/upload-payroll'
      preLoaderRoute: typeof ClientUploadPayrollRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/upload-history': {
      id: '/client/upload-history'
      path: '/upload-history'
      fullPath: '/client/upload-history'
      preLoaderRoute: typeof ClientUploadHistoryRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/queries': {
      id: '/client/queries'
      path: '/queries'
      fullPath: '/client/queries'
      preLoaderRoute: typeof ClientQueriesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/invoices': {
      id: '/client/invoices'
      path: '/invoices'
      fullPath: '/client/invoices'
      preLoaderRoute: typeof ClientInvoicesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/queries': {
      id: '/admin/queries'
      path: '/queries'
      fullPath: '/admin/queries'
      preLoaderRoute: typeof AdminQueriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll-queue': {
      id: '/admin/payroll-queue'
      path: '/payroll-queue'
      fullPath: '/admin/payroll-queue'
      preLoaderRoute: typeof AdminPayrollQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/human-review': {
      id: '/admin/human-review'
      path: '/human-review'
      fullPath: '/admin/human-review'
      preLoaderRoute: typeof AdminHumanReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dispatch': {
      id: '/admin/dispatch'
      path: '/dispatch'
      fullPath: '/admin/dispatch'
      preLoaderRoute: typeof AdminDispatchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agent': {
      id: '/admin/agent'
      path: '/agent'
      fullPath: '/admin/agent'
      preLoaderRoute: typeof AdminAgentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll-queue/$id': {
      id: '/admin/payroll-queue/$id'
      path: '/$id'
      fullPath: '/admin/payroll-queue/$id'
      preLoaderRoute: typeof AdminPayrollQueueIdRouteImport
      parentRoute: typeof AdminPayrollQueueRoute
    }
    '/admin/clients/$id': {
      id: '/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AdminClientsIdRouteImport
      parentRoute: typeof AdminClientsRoute
    }
  }
}

interface AdminClientsRouteChildren {
  AdminClientsIdRoute: typeof AdminClientsIdRoute
}

const AdminClientsRouteChildren: AdminClientsRouteChildren = {
  AdminClientsIdRoute: AdminClientsIdRoute,
}

const AdminClientsRouteWithChildren = AdminClientsRoute._addFileChildren(
  AdminClientsRouteChildren,
)

interface AdminPayrollQueueRouteChildren {
  AdminPayrollQueueIdRoute: typeof AdminPayrollQueueIdRoute
}

const AdminPayrollQueueRouteChildren: AdminPayrollQueueRouteChildren = {
  AdminPayrollQueueIdRoute: AdminPayrollQueueIdRoute,
}

const AdminPayrollQueueRouteWithChildren =
  AdminPayrollQueueRoute._addFileChildren(AdminPayrollQueueRouteChildren)

interface AdminRouteChildren {
  AdminAgentRoute: typeof AdminAgentRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminClientsRoute: typeof AdminClientsRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDispatchRoute: typeof AdminDispatchRoute
  AdminHumanReviewRoute: typeof AdminHumanReviewRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminPayrollQueueRoute: typeof AdminPayrollQueueRouteWithChildren
  AdminQueriesRoute: typeof AdminQueriesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentRoute: AdminAgentRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminClientsRoute: AdminClientsRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDispatchRoute: AdminDispatchRoute,
  AdminHumanReviewRoute: AdminHumanReviewRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminPayrollQueueRoute: AdminPayrollQueueRouteWithChildren,
  AdminQueriesRoute: AdminQueriesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientInvoicesRoute: typeof ClientInvoicesRoute
  ClientQueriesRoute: typeof ClientQueriesRoute
  ClientUploadHistoryRoute: typeof ClientUploadHistoryRoute
  ClientUploadPayrollRoute: typeof ClientUploadPayrollRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientDashboardRoute: ClientDashboardRoute,
  ClientInvoicesRoute: ClientInvoicesRoute,
  ClientQueriesRoute: ClientQueriesRoute,
  ClientUploadHistoryRoute: ClientUploadHistoryRoute,
  ClientUploadPayrollRoute: ClientUploadPayrollRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRoute,
  ClientRoute: ClientRouteWithChildren,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
