from __future__ import annotations

CANONICAL_TIMESHEET_COLUMNS: tuple[str, ...] = (
    "employee_id",
    "employee_name",
    "client_code",
    "client_name",
    "billing_period",
    "department",
    "role",
    "working_days",
    "overtime_hours",
    "overtime_amount",
    "leave_type",
    "leave_days",
    "reimbursement_amount",
    "reimbursement_reason",
    "basic",
    "housing",
    "transport",
    "food",
    "phone",
    "gross",
    "deductions",
    "net_pay",
    "currency",
)

FINAL_DATABASE_TABLES: tuple[str, ...] = (
    "clients",
    "employees",
    "payroll_master",
    "documents",
    "extracted_tables",
    "timesheets",
    "timesheet_entries",
    "validation_results",
    "review_tasks",
    "invoice_definitions",
    "invoice_fields",
    "invoices",
    "invoice_items",
    "dispatch_events",
    "audit_logs",
)
